---
title: "Lab philosophy"
---

- **People first**. We love doing science and are highly committed to do the best research we can, but also pay high attention to work-life balance. We believe we do better science if we feel balanced and fulfilled in our lives. [Happy labs are better labs](https://doi.org/10.1371/journal.pcbi.1006914). We may have families, hobbies, plans outside of the lab. Whenever permitted, we are flexible with working hours and schedules. We rest and take holidays when needed. We celebrate good news and are empathetic to life events. We accept honest failures and take them as learning opportunities. We support each other. We treat each other with respect, empathy and friendliness. In the end, we aim to be friends/colleagues who enjoy doing science together.

- **Guiding principles**. Our lab motto is "*We need less research, better research, and research done for the right reasons*" ([Altman 1994](https://doi.org/10.1136/bmj.308.6924.283)). We don't want to do research just for the sake of publishing. Our goal is to do research that helps advance our understanding of the world and ideally also contribute to make it a better place. In the process we expect to learn new things, satisfy our curiosity, produce useful results and enjoy the process. We do not compete with anyone but ourselves to do sound research, the best research we can given our circumstances and limitations. We always keep learning and improving. 

- **Reproducibility and open science**. We believe open and reproducible science is better science, in general. We believe in the power of collaboration and team work. To the extent possible, we use preprints, share data and code with all our research papers. We pay a lot of attention and effort to curate and check our data and analysis workflows, and do our best to ensure our results are reproducible, robust and rigorous. We care a lot about uncertainty (hence the name of MAYBE_lab ;-).


## Code of conduct

We deeply care about making the MAYBE_lab a safe, inclusive, welcoming, enjoyable and harassment-free experience for everyone. We try to cultivate a community with shared values, where people are comfortable exploring ideas, asking questions, and saying things like “I don’t understand” or “Why”. 

Treat others how you wish to be treated. Be considerate in speech and actions, and actively seek to acknowledge and respect the boundaries of everyone.

Please communicate if you feel uncomfortable with anything. We deeply value feedback, especially if constructive, and will do our best to improve.

We do not tolerate harassment in any form, including demeaning, discriminatory, or harassing behaviour and speech.

Take care of each other. Please share with others if you notice a dangerous situation, someone in distress, or a potential violation of this Code of Conduct. 

This Code of Conduct applies to all people participating in the MAYBE_lab. It applies to all modes of interaction in person and online including GitHub repositories and Slack.

(adapted from [rOpenSci](https://ropensci.org/code-of-conduct/))



