---
title: "Software"
---

- [BayesianNetworks](https://pakillo.github.io/BayesianNetworks/): Bayesian modelling of bipartite networks

- [network.tools](https://pakillo.github.io/network.tools/): Tools to work with bipartite networks

- [plantas-cerca-de-mi](https://frodsan.shinyapps.io/plantas-cerca-de-mi/): A shiny app to find native Iberian plants around you

- [CityShadeMapper](https://pakillo.github.io/CityShadeMapper/): Create high resolution maps of shading/insolation in cities

- [DHARMa.helpers](https://pakillo.github.io/DHARMa.helpers/): helper functions to check Bayesian brms models with DHARMa

- [easyclimate](https://verughub.github.io/easyclimate/): easy access to high-resolution daily climate data

- [grateful](https://pakillo.github.io/grateful/): facilitate citation of R packages

- [FloraIberica](https://pakillo.github.io/FloraIberica/): Taxonomic and distribution data for the vascular plants of the Iberian Peninsula and Balearic Islands

- [ANECAtools](https://pakillo.github.io/ANECAtools/): Facilitando el proceso de acreditación en la ANECA

- [labeleR](https://github.com/EcologyR/labeleR): Automatic generation of labels, certificates and much more with R

- [Lumping, splitting, or pooling taxa for niche estimation? An evaluation through computer simulations](https://github.com/Pakillo/lump.split.pool.ENM)

- [Rgis](https://pakillo.github.io/rgis/): streamlining GIS operations in R

- [rSDM](https://pakillo.github.io/rSDM/): Species Distribution Modelling in R

- [safeinstall](https://github.com/Pakillo/safeinstall): safe install of R packages from online repositories

- [vegetools](https://github.com/Pakillo/vegetools): tools for reproducible vegetation analyses

- [biblioformat](https://github.com/Pakillo/biblioformat): Revise and Reformat Plain Text Bibliographies with R

- [Effectiveness landscapes](https://github.com/pedroj/effectiveness_pckg): plotting the effectiveness landscape of plant-animal mutualisms

- [rmdTemplates](https://github.com/Pakillo/rmdTemplates): a collection of Rmarkdown templates

- [template](https://pakillo.github.io/template/): generic template for research projects structured as R packages

- [aire](https://github.com/SevillaR/aire): calidad del aire en Andalucía

- [CVtools](https://github.com/Pakillo/CVtools): tools for academic CV preparation in R & Rmarkdown

- [RmdTools](https://github.com/Pakillo/RmdTools): helper functions for Rmarkdown

- [pacotools](https://github.com/Pakillo/pacotools): Miscellaneous tools I often need and forget about





