---
title: 'Maintaining forest cover to enhance temperature buffering under future climate change'
type: 'article'
author: 'De Lombaerde, Vangansbeke, Lenoir, Van Meerbeek, Lembrechts, Rodríguez-Sánchez, Luoto, Scheffers, Haesen, Aalto, Christiansen, De Pauw, Depauw, Govaert, Greiser, Hampe, Hylander, Klinges, Koelemeijer, Meeussen, Ogée, Sanczuk, Vanneste, Zellweger, Baeten, De Frenne'
year: '2023'
publication: 'Science of The Total Environment'
preprint: 'https://biblio.ugent.be/publication/8726229/file/8726230.pdf'
doi: 'https://doi.org/10.1016/j.scitotenv.2021.151338'
pdf: 'https://biblio.ugent.be/publication/8726229/file/8726230.pdf'
data: 'https://doi.org/10.6084/m9.figshare.7604849'
# code: 'https://doi.org/10.1016/j.scitotenv.2021.151338'
toc: false
categories: 
  - climate change
  - forest dynamics
  - microclimate
---

## Citation

> De Lombaerde, E., Vangansbeke, P., Lenoir, J., Van Meerbeek, K., Lembrechts, J., Rodríguez-Sánchez, F., et al. (2022) Maintaining forest cover to enhance temperature buffering under future climate change. Science of The Total Environment, 810, 151338.

## Abstract

Forest canopies buffer macroclimatic temperature fluctuations. However, we do not know if and how the capacity of canopies to buffer understorey temperature will change with accelerating climate change. Here we map the difference (offset) between temperatures inside and outside forests in the recent past and project these into the future in boreal, temperate and tropical forests. Using linear mixed-effect models, we combined a global database of 714 paired time series of temperatures (mean, minimum and maximum) measured inside forests vs. in nearby open habitats with maps of macroclimate, topography and forest cover to hindcast past (1970–2000) and to project future (2060–2080) temperature differences between free-air temperatures and sub-canopy microclimates. For all tested future climate scenarios, we project that the difference between maximum temperatures inside and outside forests across the globe will increase (i.e. result in stronger cooling in forests), on average during 2060–2080, by 0.27 ± 0.16 °C (RCP2.6) and 0.60 ± 0.14 °C (RCP8.5) due to macroclimate changes. This suggests that extremely hot temperatures under forest canopies will, on average, warm less than outside forests as macroclimate warms. This knowledge is of utmost importance as it suggests that forest microclimates will warm at a slower rate than non-forested areas, assuming that forest cover is maintained. Species adapted to colder growing conditions may thus find shelter and survive longer than anticipated at a given forest site. This highlights the potential role of forests as a whole as microrefugia for biodiversity under future climate change.

### Publication metrics

<br>

<span class="__dimensions_badge_embed__" data-doi="10.1016/j.scitotenv.2021.151338" data-hide-zero-citations="true" data-legend="always"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script><div data-badge-details="right" data-badge-type="medium-donut" data-doi="10.1016/j.scitotenv.2021.151338" data-hide-no-mentions="true" class="altmetric-embed"></div>

<div class="scite-badge" data-doi="10.1016/j.scitotenv.2021.151338" data-layout="horizontal" data-show-zero="false" data-show-labels="true"></div><link rel="stylesheet" type="text/css" href="https://cdn.scite.ai/badge/scite-badge-latest.min.css"><script async type="application/javascript" src="https://cdn.scite.ai/badge/scite-badge-latest.min.js"></script>

