---
title: 'Cenozoic climate changes and the demise of Tethyan laurel forests: lessons for the future from an integrative reconstruction of the past'
type: 'article'
author: 'Rodríguez-Sánchez, Arroyo'
year: '2011'
publication: 'Climate Change, Ecology and Systematics'
# preprint: 'https://doi.org/10.1017/CBO9780511974540.014'
doi: 'https://doi.org/10.1017/CBO9780511974540.014'
pdf: 'https://frodriguezsanchez.net/pdf/Rodriguez-Sanchez_CCES_2011.pdf'
# data: 'https://doi.org/10.1017/CBO9780511974540.014'
# code: 'https://doi.org/10.1017/CBO9780511974540.014'
toc: false
categories: 
  - book chapter
  - review
  - refugia
  - biogeography
  - species distribution modelling
  - phylogeography
  - palaeoecology
  - laurel forests
---

## Citation

> Rodríguez-Sánchez, F. & Arroyo, J. (2011) Cenozoic climate changes and the demise of Tethyan laurel forests: lessons for the future from an integrative reconstruction of the past. Climate Change, Ecology and Systematics, 280–303.

## Abstract

Climate on earth has always been changing. Despite decades of investigation, our limited knowledge of the ecological and evolutionary effects of climate changes often translates into uncertain predictions about the impact of future climates on biodiversity. Integrative biogeographical approaches using palaeobotanical, phylogenetic and niche-based species distribution models, when permitted by data availability, may provide valuable insights to address these key questions. Here we combine palaeobotanical and phylogeographical information with hindcast modelling of species distribution changes to reconstruct past range dynamics and differentiation in the bay laurel (Laurus spp., Lauraceae), an emblematic relict tree from the subtropical laurel forests that thrived in Tethyan realms during most of the Tertiary period. We provide plausible examples of climate-driven migration, extinction and persistence of populations and taxa, and discuss the factors that influence niche conservatism or adaptation to changing environments. Finally, we discuss the likely impacts of the predicted climate change on laurophyllous taxa in the Mediterranean and Macaronesia.

### Publication metrics

<br>

<span class="__dimensions_badge_embed__" data-doi="10.1017/CBO9780511974540.014" data-hide-zero-citations="true" data-legend="always"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script><div data-badge-details="right" data-badge-type="medium-donut" data-doi="10.1017/CBO9780511974540.014" data-hide-no-mentions="true" class="altmetric-embed"></div>

<div class="scite-badge" data-doi="10.1017/CBO9780511974540.014" data-layout="horizontal" data-show-zero="false" data-show-labels="true"></div><link rel="stylesheet" type="text/css" href="https://cdn.scite.ai/badge/scite-badge-latest.min.css"><script async type="application/javascript" src="https://cdn.scite.ai/badge/scite-badge-latest.min.js"></script>

